### ISSUE TITLE
Renaming of instance files

### ISSUE THREAD

**Issue by relund** [MCDMSociety/MOrepo-Forget20#1]
The instance files must be renamed. I suggest `Forget20-[problem class]_[variables]_[objectives]_[range of costs]_[cost generation method]_[constaint id]_[id].raw` where 

- [problem class]: AP, FLP[e|h], KP
- [range of costs]: written with a dash e.g. 1-1000
- [cost generation method]: random, spheredown, sphereup, 2box
- [costaint id]: Same id if constraints are the same
- [id]: Instance id within same constraint id. 

Any other suggestions? 

Note also the instance files must also be included in a subfolder for each problem class.

**Comment by NicolasJForget** [comment]
Test instances in github renamed, waiting to retrieve the rest of the instances to rename all of them and close the issue.

**Comment by relund** [comment]
To be consistent I think you should use problem class names KP (knapsack problem), AP (assignment problem), FLP (facility location problem) or IP (integer problem with binary variables). Note drop [e|h] for the FLP. This is not input specific as we first know if the problem is easy/hard after solving it. You may instead for the FLP use to ranges of cost e.g. 1-1000_1-10.

**Comment by NicolasJForget** [comment]
Names changed in the output files as well. I close the issue.
