### ISSUE TITLE
Generation of random IPs

### ISSUE THREAD

**Issue by relund** [MCDMSociety/MOrepo-Forget20#12]
These need to be generated and tested. Suggestions for how?

**Comment by SuneGadegaard** [comment]
https://minerva-access.unimelb.edu.au/bitstream/handle/11343/233868/5643bc20-dcc2-e911-94a8-0050568d7800_200107-sb-thesis-final-unsigned.pdf?sequence=1&isAllowed=y

**Comment by relund** [comment]
Do not test IPs
