### ISSUE TITLE
Update ReadMe with instance desc

### ISSUE THREAD

**Issue by relund** [MCDMSociety/MOrepo-Forget20#2]
The readme file need a description of instance names and the raw format.

**Comment by NicolasJForget** [comment]
Instance description added. However the shape of the description in the ReadMe.md may not be the most satisfactory: do we have some conventions about how to nicely define an instance description in a ReadMe file ?

**Comment by relund** [comment]
I don't think there is any conventions. It should just be easy understandable and not to long. I have edited the file a bit.

**Comment by relund** [comment]
To be consistent I have edited the ReadMe so use camel notation e.g. constraint_matrix -> constraintMatrix. You may close this issue when you think the ReadMe is okay.
