### ISSUE TITLE
Update report with input and output statistics

### ISSUE THREAD

**Issue by relund** [MCDMSociety/MOrepo-Forget20#3]
See sec 2.1-2.2

**Comment by NicolasJForget** [comment]
Regarding the input statistics, should I introduce all the statistics used in stat.csv and the other output files ? (pro : anyone can understand the stat.csv file; con : it may be a lot of information and overload a bit the reader) Or should I introduce only those that appear in the report ? (just the opposite pro and cons)

**Comment by relund** [comment]
I think all of them. The report is mainly for Sune and I. In the paper we of course won't introduce all.

**Comment by NicolasJForget** [comment]
Statistics added. The names that involve instance name will be 100% relevant when the renaming of the instance will be done. (need to rename some output files to be consistent with the instance names)
